name: first workflow
on: push
jobs:
  project_setup:
    runs-on: ubuntu-latest
    steps:
      - run: install build
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - run: npm test
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - run: npx eslint .